<a href="https://colab.research.google.com/github/bhavanachintha/Python-1-/blob/master/Day_11_(28_06_19).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to OOP in Python
**one of the popular approach to solve a programming probleb by creating an objects. This is known as Object Oriented Programming.     
An object has two characterstics:    
1.attributes(name,age,colour)   
2.behaviour(learn,study,singing,dance)   

**In Python, the concept OOP follow these things:   

1.Inheritance  
2.Encapsulation    #(wraping data into single unit)    
3.Ploymorphism  
 
**Class:  
A class is blueprint for the object or  logical entity   

**Object:    
Blue print of class or instance of the class or physical entity  

**Methods:    
 part of class and can be called with object    
 
 **Constructors:    
 Part of class  and can be called automatically when the class object is created   




In [0]:
class classname:
      #some functions and variables
      #Function-- used to perform the specific activity
       # variables -- Data(memory)

In [0]:
def test():
    print('test() for funtion')
    return
test()

test() for funtion


In [0]:
class demo:
  def test(self):
      print("test() for the class and method")
      return
obj= demo()
obj.test()

test() for the class and method


In [0]:
class demo1:
   def fact(self,n):
       #return the factorial
        fact=1
        while(n!=0):
          fact=fact*n
          n=n-1
        return fact
      
p1=demo1()
p1.fact(5)#120

120

In [0]:
# Method 
# def test(self,para1,para2)

In [0]:
class demo2:
     
     def accept(self,p1,p2):
         a=p1
         b=p2
         return
     def display(self):
         print("a= ",a)
         print("b= ",b)
        
c1=demo2()
c1.accept(10,20)
c1.display()

In [0]:
class demo2:
   def __init__(self,p1,p2):
       self.p1=p1
       self.p2=p2
      
   def add(self,p1,p2):
       return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))

300


In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)


[1 2 3 4]


In [0]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)                         
print(array.dtype)

(4,)
int64


In [0]:
lst=[1.0,2.4,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
float64


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np


(2, 3)


In [0]:
#re-shape the given array
# numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#append some data ---  horizontally
# hstack (array1,array2)--- will be automatically arranged in horizontally
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [0]:
#appen some data--- vertical
#vstack(array1,array2)-- will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
#generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.75430782 4.28905235 5.1004348  5.37494129 4.54883259 4.83715935
 4.57656634 4.59673403 5.44543878 5.04452109]


In [0]:
#number.zeroes() and numpy.one()
#generate an array with all zeroes-- numpy.zeroes()
#numpy.zeros(shape,dtype=float,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [0]:
#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:
#arrange()--particular
#numpy.arrange(start,end,step)
#start-value
#end-value
#step-gap between one value to another value

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:
np.arange(2,20,2)
np.arange(1,25,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
#indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)


[[1 2 3]
 [4 5 6]]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing coloumn:",a1[:,1])

slicing coloumn: [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column :",a1[:,2])

slicing last column : [3 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(" row and column:",a1[1,:2])

 row and column: [4 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[1,:1])

first row: [4]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[1][1])

first row: 5


In [0]:
a1=np.random.normal(5,1,10)
print(a1)

[4.67539374 5.56552424 3.61088327 6.05532476 6.21546607 5.29175991
 5.0955593  5.22465369 3.7198674  4.8365804 ]


In [0]:
#some math operation in given random numbers
#min -- returns the least number
#max-- returns the large number
#mean--- mean
#median---median
#GD -- gaussian distribution
a1=np.random.normal(5,1,10)
print(a1)
print("min value= ",np.min(a1))
print("max value= ",np.max(a1))
print("mean value= ",np.mean(a1))
print("median value= ",np.median(a1))


[4.66446951 3.11518563 4.36727912 5.14322714 3.63293804 6.25974457
 5.89160354 5.76205622 5.50072232 4.63691853]
min value=  3.1151856342300093
max value=  6.259744566424472
mean value=  4.897414462256462
median value=  4.903848324349939


In [0]:
#multiply  of 1D arrays
#numpy.dot(x,y)---

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [0]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

# Pandas Basics
 Python is one of the popular programming language for data analysis<br>    
Python is offering the Lib called Pandas used for importing and analysing pretty much faster and easier also        
Pandas DataFrames        
    
    Data Analysis with Python

In [0]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)
    

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd
